x-common:
  environment: &os_env
    OS_CLOUD: openstack-internal
    OS_INTERFACE: internal
    KEYSTONE_INTERNAL_URL: http://keystone:5000
    KEYSTONE_PUBLIC_URL: "${KEYSTONE_PUBLIC_URL:-http://keystone:5000}"

services:
  database:
    image: docker.io/mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    secrets:
      - mariadb-root-password
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mariadb/scripts:/scripts"
    healthcheck:
      test: ["CMD", "sh", "/scripts/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s

  cache:
    image: docker.io/memcached:${MEMCACHE_VERSION:-latest}

  keystone-init-db:
    image: docker.io/mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    secrets:
      - mariadb-root-password
      - keystone-db-password
    volumes:
      - "./common/scripts:/scripts/common"
    command: >
      sh /scripts/common/create-database.sh keystone keystone /run/secrets/keystone-db-password

  keystone:
    depends_on:
      keystone-init-db:
        condition: service_completed_successfully
    image: quay.io/tripleomastercentos9/openstack-keystone:${TRIPLEO_TAG:-current-tripleo}
    ports:
      - "${LISTEN_ADDRESS:-127.0.0.1}:5000:5000"
    entrypoint: ["sh", "/entrypoint.sh"]
    command: ["/usr/sbin/httpd", "-DFOREGROUND"]
    volumes:
      - "./keystone/entrypoint.sh:/entrypoint.sh"
      - "./keystone/scripts:/scripts"
      - "./common/scripts:/scripts/common"
      - "config:/config"
    environment:
      <<: *os_env
      OS_CLOUD: openstack
    secrets:
      - mariadb-root-password
      - keystone-db-password
      - keystone-admin-password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s

  ironic-init-db:
    image: docker.io/mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    secrets:
      - mariadb-root-password
      - ironic-db-password
    volumes:
      - "./common/scripts:/scripts/common"
    command: >
      sh /scripts/common/create-database.sh ironic ironic /run/secrets/ironic-db-password

  ironic-api:
    depends_on:
      ironic-init-db:
        condition: service_completed_successfully
    image: quay.io/tripleomastercentos9/openstack-ironic-api:${TRIPLEO_TAG:-current-tripleo}
    ports:
      - "${LISTEN_ADDRESS:-127.0.0.1}:6385:6385"
    user: root
    entrypoint: ["sh", "/entrypoint.sh"]
    command: ["ironic-api"]
    volumes:
      - "./ironic/entrypoint.sh:/entrypoint.sh"
      - "./ironic/scripts:/scripts/ironic"
      - "./common/scripts:/scripts/common"
      - "config:/config"
    environment:
      <<: *os_env
      IRONIC_INTERNAL_URL: http://ironic:6385
      IRONIC_PUBLIC_URL: "${IRONIC_PUBLIC_URL:-http://ironic:6384}"
    secrets:
      - mariadb-root-password
      - keystone-admin-password
      - ironic-db-password
      - ironic-keystone-password

  neutron-init-db:
    image: docker.io/mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    secrets:
      - mariadb-root-password
      - neutron-db-password
    volumes:
      - "./common/scripts:/scripts/common"
    command: >
      sh /scripts/common/create-database.sh neutron neutron /run/secrets/neutron-db-password

volumes:
  config:
  db_data:

secrets:
  mariadb-root-password:
    file: secrets/mariadb-root-password
  keystone-db-password:
    file: secrets/keystone-db-password
  keystone-admin-password:
    file: secrets/keystone-admin-password
  ironic-db-password:
    file: secrets/ironic-db-password
  ironic-keystone-password:
    file: secrets/ironic-keystone-password
  neutron-db-password:
    file: secrets/neutron-db-password
  neutron-keystone-password:
    file: secrets/neutron-keystone-password
